edges:
  - from: 'eng2_73B2'
    to: 'eng2_7FElevator'
    behavior_type: 'spot_person_lead_behaviors.narrow_behavior.NarrowBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: 'eng2_7FElevator'
    to: 'eng2_73B2'
    behavior_type: 'spot_person_lead_behaviors.narrow_behavior.NarrowBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: 'eng2_7FElevator'
    to: 'eng2_2FElevator'
    behavior_type: 'spot_person_lead_behaviors.elevator_behavior.ElevatorBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
      rest_waypoint_id: 'unsaid-collie-jvatvS.7KX9jpzQz61GL4A=='
      goal_waypoint_id: 'shelfy-dassie-vK9Tf3cAQpdA.25gPJl8OQ=='
  - from: 'eng2_2FElevator'
    to: 'eng2_7FElevator'
    behavior_type: 'spot_person_lead_behaviors.elevator_behavior.ElevatorBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
      rest_waypoint_id: 'unsaid-collie-jvatvS.7KX9jpzQz61GL4A=='
      goal_waypoint_id: 'sly-chetah-IZ4pVY7vrqO36OoKCYk9Zg=='
  - from: 'eng2_2FElevator'
    to: 'eng2_MainEntrance_upper'
    behavior_type: 'spot_person_lead_behaviors.narrow_behavior.NarrowBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_2FElevator_to_MainEntrance.walk'
  - from: 'eng2_MainEntrance_upper'
    to: 'eng2_2FElevator'
    behavior_type: 'spot_person_lead_behaviors.narrow_behavior.NarrowBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_2FElevator_to_MainEntrance.walk'
  - from: 'eng2_MainEntrance_upper'
    to: 'eng2_MainEntrance_lower'
    behavior_type: 'spot_person_lead_behaviors.stair_behavior.StairBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
      stair_nums:
        - -10
        - -10
  - from: 'eng2_MainEntrance_lower'
    to: 'eng2_MainEntrance_upper'
    behavior_type: 'spot_person_lead_behaviors.stair_behavior.StairBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
      stair_nums:
        - 10
        - 10
  - from: 'eng2_MainEntrance_lower'
    to: 'eng2_MainEntrance_outer'
    behavior_type: 'spot_person_lead_behaviors.crosswalk_behavior.CrosswalkBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
  - from: 'eng2_MainEntrance_outer'
    to: 'eng2_MainEntrance_lower'
    behavior_type: 'spot_person_lead_behaviors.crosswalk_behavior.CrosswalkBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
  - from: 'eng2_MainEntrance_outer'
    to: 'HongoMainGate'
    behavior_type: 'spot_person_lead_behaviors.walk_behavior.WalkBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
  - from: 'HongoMainGate'
    to: 'eng2_MainEntrance_outer'
    behavior_type: 'spot_person_lead_behaviors.walk_behavior.WalkBehavior'
    cost: 10
    args:
      graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
nodes:
  'eng2_73B2':
    name_en: '73B2'
    name_jp: '7 3 B 2'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'dyed-bat-t00VKo5XixLihCvpsZPRqw=='
        localization_method: 'fiducial'
  'eng2_7FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'looted-cougar-RWT2C0zLJXG.ezYnCuLUeQ=='
        localization_method: 'fiducial'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
        id: 'sly-chetah-IZ4pVY7vrqO36OoKCYk9Zg=='
        localization_method: 'fiducial'
    switchbot_device: '/eng2/7f/elevator/down/button'
    floor: 7
    floor_height: 24
  'eng2_2FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_2FElevator_to_MainEntrance.walk'
        id: 'mythic-leech-Uslc00eTIhygFsCdH2q1Qg=='
        localization_method: 'fiducial'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
        id: 'shelfy-dassie-vK9Tf3cAQpdA.25gPJl8OQ=='
        localization_method: 'fiducial'
    switchbot_device: '/eng2/2f/elevator/up/button'
    floor: 2
    floor_height: 0
  'eng2_MainEntrance_upper':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_2FElevator_to_MainEntrance.walk'
        id: 'violet-ibis-HtCPm39SIDSzoJFVX88S+A=='
        localization_method: 'fiducial'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate.walk'
        id: 'about-goat-EHRLqkk7XWmMXAdfcXHP5g=='
        localization_method: 'fiducial'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
        id: 'ahead-mink-Fml31k5vw.Y2XR.7v1BSeg=='
        localization_method: 'fiducial'
  'eng2_MainEntrance_lower':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate.walk'
        id: 'aft-tick-clWAq8obxtWm64bTthYwMQ=='
        localization_method: 'waypoint'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
        id: 'rested-grouse-GzVp6htKyt6kdIcS+Tu6aA=='
        localization_method: 'waypoint'
  'eng2_MainEntrance_outer':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate.walk'
        id: 'tilled-weevil-slAZLtX3U2NcqaINkGY0Sw=='
        localization_method: 'waypoint'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
        id: 'sown-pincer-NcgfKhWf9H+B3yWIKA8W7A=='
        localization_method: 'waypoint'
  'HongoMainGate':
    name_en: 'Maingate'
    name_jp: '正門'
    waypoints_on_graph:
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate.walk'
        id: 'aglow-gadfly-tSusAUqUNtqVaKFO49pDbQ=='
        localization_method: 'waypoint'
      - graph: '$(find spot_autowalk_data)/autowalk/eng2_MainEntrance_to_HongoMainGate_Daylight.walk'
        id: 'regal-bison-qmAA7fyZh10L2bzoTNqUFQ=='
        localization_method: 'waypoint'
