standalone_tags:
  [
    {id: 0, size: 0.02, name: "t_sawada"},
    {id: 1, size: 0.02, name: "obinata"},
    {id: 2, size: 0.02, name: "hasegawa"},
    {id: 3, size: 0.02, name: "tsubaki"},
    {id: 4, size: 0.02, name: "nagata"}
  ]
