edges:
  - from: '7FElevator'
    to: 'eng2_2FElevator'
    type: 'go_alone_and_wait'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
  - from: 'eng2_2FElevator'
    to: '7FElevator'
    type: 'go_alone_and_wait'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
  - from: '7FElevator'
    to: 'eng2_2FElevator'
    type: 'elevator'
    cost: 5
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
      rest_waypoint_id: 'unsaid-collie-jvatvS.7KX9jpzQz61GL4A=='
  - from: 'eng2_2FElevator'
    to: '7FElevator'
    type: 'elevator'
    cost: 5
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
      rest_waypoint_id: 'unsaid-collie-jvatvS.7KX9jpzQz61GL4A=='
  - from: '73B2'
    to: '7FElevator'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '7FElevator'
    to: '73B2'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73B2'
    to: '73A2'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73A2'
    to: '73B2'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '7FElevator'
    to: '73A2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73A2'
    to: '7FElevator'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73B2'
    to: '7FstairTo8F'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '7FstairTo8F'
    to: '73B2'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '7FstairTo8F'
    to: '8FstairTo7F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '8FstairTo7F'
    to: '7FstairTo8F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '8FstairTo7F'
    to: '81C1'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '81C1'
    to: '8FstairTo7F'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: 'eng2_2FElevator'
    to: 'eng2_MainEntrance_upper'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_upper'
    to: 'eng2_2FElevator'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_lower'
    to: 'eng2_MainEntrance_upper'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_upper'
    to: 'eng2_MainEntrance_lower'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_lower'
    to: 'eng2_MainEntrance_outer'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_outer'
    to: 'eng2_MainEntrance_lower'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'HongoMainGate'
    to: 'eng2_MainEntrance_outer'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_MainEntrance_outer'
    to: 'HongoMainGate'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
  - from: 'eng2_2FElevator'
    to: 'eng2_Entrance_to_eng8'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng2_Entrance_to_eng8'
    to: 'eng2_2FElevator'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng2_Entrance_to_eng8'
    to: 'eng2_Entrance_to_eng8_outside'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng2_Entrance_to_eng8_outside'
    to: 'eng2_Entrance_to_eng8'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng2_Entrance_to_eng8_outside'
    to: 'bicycle_parking_eng6_lower'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'bicycle_parking_eng6_lower'
    to: 'eng2_Entrance_to_eng8_outside'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'bicycle_parking_eng6_lower'
    to: 'eng_TelephoneBox'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng_TelephoneBox'
    to: 'bicycle_parking_eng6_lower'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_Entrance'
    to: 'eng_TelephoneBox'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng_TelephoneBox'
    to: 'eng8_Piloti_Entrance'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_Entrance'
    to: 'eng8_Piloti_Center'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_Center'
    to: 'eng8_Piloti_Entrance'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_Center'
    to: 'eng8_Piloti_stair_below'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_stair_below'
    to: 'eng8_Piloti_Center'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_stair_above'
    to: 'eng8_Piloti_stair_below'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_stair_below'
    to: 'eng8_Piloti_stair_above'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_Piloti_stair_above'
    to: 'eng8_2FElevator'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng8_2FElevator'
    to: 'eng8_Piloti_stair_above'
    type: 'narrow'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
  - from: 'eng_TelephoneBox'
    to: 'eng1_eastside'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng1_eastside'
    to: 'eng_TelephoneBox'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng1_eastside'
    to: 'eng1_eastside_square'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng1_eastside_square'
    to: 'eng1_eastside'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng1_eastside_square'
    to: 'eng_square_eastnorthpoint'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng_square_eastnorthpoint'
    to: 'eng1_eastside_square'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng_square_eastnorthpoint'
    to: 'eng_square_westnorthpoint'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng_square_westnorthpoint'
    to: 'eng_square_eastnorthpoint'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'eng_square_westnorthpoint'
    to: 'starbucks_front'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'starbucks_front'
    to: 'eng_square_westnorthpoint'
    type: 'crosswalk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'starbucks_front'
    to: 'HongoMainGate'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
  - from: 'HongoMainGate'
    to: 'starbucks_front'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
nodes:
  '73B2':
    name_en: '73B2'
    name_jp: '73B2'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'dyed-bat-t00VKo5XixLihCvpsZPRqw=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'fuzzed-medusa-wyXWCEjmWas1kMo8EJW8Bw=='
        localization_method: 'fiducial'
  '73A2':
    name_en: '73A2'
    name_jp: '73A2'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'affine-drake-Jfb0ZPtNcqcrq9yhnEl2DA=='
        localization_method: 'fiducial'
  '7FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'looted-cougar-RWT2C0zLJXG.ezYnCuLUeQ=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
        id: 'larger-mudcat-0x3bt3Dif.1QU9JfXpyQPw=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
        id: 'sly-chetah-IZ4pVY7vrqO36OoKCYk9Zg=='
        localization_method: 'fiducial'
    switchbot_device: '/eng2/7f/elevator/down/button'
    floor: 7
  '7FstairTo8F':
    name_en: 'Stair'
    name_jp: '階段'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'aired-wrasse-UmViHfVK68XNKfnezv8UCQ=='
        localization_method: 'waypoint'
  '8FstairTo7F':
    name_en: 'Stair'
    name_jp: '階段'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'effete-chunga-cGupHFfePR3KKRTBQ.XU4Q=='
        localization_method: 'waypoint'
  '81C1':
    name_en: '81C1'
    name_jp: '81C1'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'crazed-vole-M0n4MLiK9XpQEhTHodXtmw=='
        localization_method: 'fiducial'
  'eng2_2FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
        id: 'rainy-collie-uwFW2KVYg2YCUi8FF6N00g=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_2FEntrance.walk'
        id: 'snaky-beagle-.fmRm2JflzlV6Dv5fTdnIQ=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
        id: 'banner-oxen-UrEwTUbZYL0IQnY5TCFwrA=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_elevator_7FElevator_to_2FElevator.walk'
        id: 'shelfy-dassie-vK9Tf3cAQpdA.25gPJl8OQ=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'inland-remora-FqtX8ScP+.inEd4xFYKq4A=='
        localization_method: 'fiducial'
    switchbot_device: '/eng2/2f/elevator/up/button'
    floor: 2
  'eng2_MainEntrance_upper':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
        id: 'sown-eel-fcPD.nqdAAv5EP23gzftqA=='
        localization_method: 'waypoint'
  'eng2_MainEntrance_lower':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
        id: 'dummy-isopod-8jheUWJFFD7iQ3NXMXTWFg=='
        localization_method: 'waypoint'
  'eng2_MainEntrance_outer':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
        id: 'gifted-taipan-i3YcwQS4hjHWoC69kSCMsA=='
        localization_method: 'waypoint'
  'HongoMainGate':
    name_en: 'Maingate'
    name_jp: '正門'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_MainGate.walk'
        id: 'wobbly-macaw-YHBHKCQPbVkWFdDSrFO3Gw=='
        localization_method: 'waypoint'
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'scabby-gibbon-6xcOMWNTVIXmDJ2EB6GHXw=='
        localization_method: 'fiducial'
  'eng2_Entrance_to_eng8':
    name_en: 'entrance'
    name_jp: 'エントランス'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'slain-magpie-K5jahfbkqwM.su8GIZUyLw=='
        localization_method: 'fiducial'
  'eng2_Entrance_to_eng8_outside':
    name_en: 'entrance'
    name_jp: 'エントランス'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'above-puffin-100RMl4r9V.ujhdP8gYa3w=='
        localization_method: 'waypoint'
  'bicycle_parking_eng6_lower':
    name_en: 'bicycle_parking'
    name_jp: '駐輪場下'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'gowned-dingo-oKoVgFPXF2eecyPVriBDpA=='
        localization_method: 'waypoint'
  'eng_TelephoneBox':
    name_en: 'telephone box'
    name_jp: '電話ボックス'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'slain-pika-VdtPz3lWcp5T+pEArUB3PA=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'aired-hyrax-BF+hXHaUufi.DLd3pEWm5Q=='
        localization_method: 'fiducial'
  'eng8_Piloti_Entrance':
    name_en: 'Piloti'
    name_jp: 'ピロティ'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'untidy-pigeon-Alwyk8DVKL1ROYyHHKD+xQ=='
        localization_method: 'waypoint'
  'eng8_Piloti_Center':
    name_en: 'Piloti'
    name_jp: 'ピロティ'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'azoic-lion-Iapbto7rzlzuFF0MvXdyPA=='
        localization_method: 'fiducial'
  'eng8_Piloti_stair_below':
    name_en: 'Piloti'
    name_jp: 'ピロティ'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'forte-ram-wWTPMTBRsY3KMxLOychvuQ=='
        localization_method: 'waypoint'
  'eng8_Piloti_stair_above':
    name_en: 'Piloti'
    name_jp: 'ピロティ'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'veined-weevil-mamBzsO9XuxkAYE3WigbQQ=='
        localization_method: 'waypoint'
  'eng8_2FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_eng8_2FElevator.walk'
        id: 'afeard-frog-vhsz6u.NAnlyKwGcaMCI+Q=='
        localization_method: 'fiducial'
  'eng1_eastside':
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'rabid-basset-i8S27Fm4hNZ7nXCaNnpg0A=='
        localization_method: 'waypoint'
  'eng1_eastside_square':
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'dyed-leech-jG.RWrdrKNCEjyHqdHyuaw=='
        localization_method: 'waypoint'
  'eng_square_eastnorthpoint':
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'setose-cocoon-s.opQAe8rPGrM7NzXXurLQ=='
        localization_method: 'waypoint'
  'eng_square_westnorthpoint':
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'analog-hydra-OHqbbrjChrVyH59Bn8X6Vw=='
        localization_method: 'waypoint'
  'starbucks_front':
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng_TelephoneBox_to_HongoMainGate.walk'
        id: 'tubed-isopod-T1WXNMuaEjGlAV.D36WuZQ=='
        localization_method: 'waypoint'
