pcm.uac_demo {
    type plug
    slave.pcm {
        type hw
        card UACDemoV10
        device 0
    }
}

ctl.uac_demo {
    type hw
    card UACDemoV10
}

pcm.respeaker {
  type hw
  card ArrayUAC10
  device 0
}

ctl.respeaker {
  type hw
  card ArrayUAC10
}
