- floor: 8
  altitude: 32.5
  map_name: '/eng2/8f'
- floor: 7
  altitude: 28
  map_name: '/eng2/7f'
- floor: 6
  altitude: 23.5
  map_name: '/eng2/6f'
- floor: 5
  altitude: 19.0
  map_name: '/eng2/5f'
- floor: 4
  altitude: 13.5
  map_name: '/eng2/4f'
- floor: 3
  altitude: 9
  map_name: '/eng2/3f'
- floor: 2
  altitude: 4.5
  map_name: '/eng2/2f'
- floor: 1
  altitude: 0
  map_name: '/eng2/1f'
