- floor: 7
  altitude: 4
  map_name: '/eng2/7f'
  door_frame_id: '/elevator_door_frame'
  outside_pose:
    frame_id: '/outside_frame'
    position: [0, 0, -0.000]
    orientation: [0.000, 0.000, 0, 1.0]
  inside_pose:
    frame_id: '/inside_frame'
    position: [0, 0, 0]
    orientation: [0, 0, 0, 1.0]
  buttons:
    down: '/eng2/7f/elevator_bot_down'
- floor: 3
  altitude: -15
  map_name: '/eng2/3f'
  door_frame_id: '/elevator_door_frame'
  outside_pose:
    frame_id: '/outside_frame'
    position: [0, 0, 0]
    orientation: [0, 0, 0, 1.0]
  inside_pose:
    frame_id: '/inside_frame'
    position: [0, 0, 0]
    orientation: [0, 0, 0, 1.0]
  buttons:
    up: '/eng2/3f/elevator_bot_up'
