edges:
  - from: '73B2'
    to: '7FElevator'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
      start_id: 'slangy-vulture-olJ4jnBPrLhoJBMxDFtD1w=='
      end_id: 'mum-eel-fcK.PVxkJ2GxrBDlKq+ZQg=='
      localization_method: 'fiducial'
  - from: '7FElevator'
    to: '73B2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
      start_id: 'mum-eel-fcK.PVxkJ2GxrBDlKq+ZQg=='
      end_id: 'slangy-vulture-olJ4jnBPrLhoJBMxDFtD1w=='
      localization_method: 'fiducial'
  - from: '73B2'
    to: '7FstairTo8F'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'fuzzed-medusa-wyXWCEjmWas1kMo8EJW8Bw=='
      end_id: 'largo-viper-Q1w9dqqCbIjvKBAa1tI+3Q=='
      localization_method: 'fiducial'
  - from: '7FstairTo8F'
    to: '73B2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'largo-viper-Q1w9dqqCbIjvKBAa1tI+3Q=='
      end_id: 'fuzzed-medusa-wyXWCEjmWas1kMo8EJW8Bw=='
      localization_method: 'pose'
  - from: '7FstairTo8F'
    to: '8FstairTo7F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'largo-viper-Q1w9dqqCbIjvKBAa1tI+3Q=='
      end_id: 'elite-frog-d3ttmqTPmAZ5vkfrNtc3lA=='
      localization_method: 'pose'
  - from: '8FstairTo7F'
    to: '7FstairTo8F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'elite-frog-d3ttmqTPmAZ5vkfrNtc3lA=='
      end_id: 'largo-viper-Q1w9dqqCbIjvKBAa1tI+3Q=='
      localization_method: 'pose'
  - from: '8FstairTo7F'
    to: '81C1'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'elite-frog-d3ttmqTPmAZ5vkfrNtc3lA=='
      end_id: 'crazed-vole-M0n4MLiK9XpQEhTHodXtmw=='
      localization_method: 'pose'
  - from: '81C1'
    to: '8FstairTo7F'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73b2_to_81c1_night.walk'
      start_id: 'crazed-vole-M0n4MLiK9XpQEhTHodXtmw=='
      end_id: 'elite-frog-d3ttmqTPmAZ5vkfrNtc3lA=='
      localization_method: 'pose'
nodes:
  - name: '73B2'
  - name: '7FElevator'
  - name: '7FstairTo8F'
