edges:
  - from: '2FElevator'
    to: '2FEntrance'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_2FEntrance.walk'
  - from: '2FEntrance'
    to: '2FElevator'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_2FEntrance.walk'
  - from: '7FElevator'
    to: '2FElevator'
    type: 'go_alone_and_wait'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
  - from: '2FElevator'
    to: '7FElevator'
    type: 'go_alone_and_wait'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
  - from: '73B2'
    to: '7FElevator'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '7FElevator'
    to: '73B2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73B2'
    to: '73A2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73A2'
    to: '73B2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '7FElevator'
    to: '73A2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73A2'
    to: '7FElevator'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
  - from: '73B2'
    to: '7FstairTo8F'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '7FstairTo8F'
    to: '73B2'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '7FstairTo8F'
    to: '8FstairTo7F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '8FstairTo7F'
    to: '7FstairTo8F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '8FstairTo7F'
    to: '81C1'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '81C1'
    to: '8FstairTo7F'
    type: 'walk'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '7FstairTo8F'
    to: '8FstairTo7F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
  - from: '8FstairTo7F'
    to: '7FstairTo8F'
    type: 'stair'
    cost: 10
    args:
      graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
nodes:
  '73B2':
    name_en: '73B2'
    name_jp: '73B2'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'dyed-bat-t00VKo5XixLihCvpsZPRqw=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'fuzzed-medusa-wyXWCEjmWas1kMo8EJW8Bw=='
        localization_method: 'fiducial'
  '73A2':
    name_en: '73A2'
    name_jp: '73A2'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'affine-drake-Jfb0ZPtNcqcrq9yhnEl2DA=='
        localization_method: 'fiducial'
  '7FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_7FElevator.walk'
        id: 'looted-cougar-RWT2C0zLJXG.ezYnCuLUeQ=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
        id: 'larger-mudcat-0x3bt3Dif.1QU9JfXpyQPw=='
        localization_method: 'fiducial'
  '7FstairTo8F':
    name_en: 'Stair'
    name_jp: '階段'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'aired-wrasse-UmViHfVK68XNKfnezv8UCQ=='
        localization_method: 'waypoint'
  '8FstairTo7F':
    name_en: 'Stair'
    name_jp: '階段'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'effete-chunga-cGupHFfePR3KKRTBQ.XU4Q=='
        localization_method: 'waypoint'
  '81C1':
    name_en: '81C1'
    name_jp: '81C1'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_73B2_to_81C1.walk'
        id: 'crazed-vole-M0n4MLiK9XpQEhTHodXtmw=='
        localization_method: 'fiducial'
  '2FElevator':
    name_en: 'Elevator'
    name_jp: 'エレベーター'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_7FElevator_to_2FElevator.walk'
        id: 'rainy-collie-uwFW2KVYg2YCUi8FF6N00g=='
        localization_method: 'fiducial'
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_2FEntrance.walk'
        id: 'snaky-beagle-.fmRm2JflzlV6Dv5fTdnIQ=='
        localization_method: 'fiducial'
  '2FEntrance':
    name_en: 'Entrance'
    name_jp: '入り口'
    waypoints_on_graph:
      - graph: '$(find spot_person_leader)/autowalk/eng2_2FElevator_to_2FEntrance.walk'
        id: 'ended-conch-2XbkwOkQkvye4OZcmL89pQ=='
        localization_method: 'fiducial'
