#!/usr/bin/env python

#!/usr/bin/env python
import sys

from rqt_gui.main import Main

import roslib
pkg = 'drc_task_common'

import imp
try:
    imp.find_module(pkg)
except:
    roslib.load_manifest(pkg)


plugin = 'vehicle_ui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
