(define
 (problem house-keeping)
 (:domain room-domain)
 (:objects
  (room73a1
   bookshelf
   counter
   kitchen
   sink
   drawer
   dishwasher
   fridge
   table
   start
   -
   spot)
  (bottle - item)
  (larm rarm - arm))
 (:init
  ((= (find-cost) 50)
   (= (door-cost) 10)
   (= (total-cost) 0)
   (= (manip-cost cleaner arms) 30)
   (= (manip-cost cleaner rarm) 10)
   (= (manip-cost cleaner larm) 10)
   (= (manip-cost bottle arms) 30)
   (= (manip-cost bottle rarm) 10)
   (= (manip-cost bottle larm) 10)
   (robot-at start)
   (on bottle table)
   (= (distance somewhere somewhere) 1000)
   (= (distance room73a1 room73a1) 1000)
   (= (distance bookshelf bookshelf) 1000)
   (= (distance counter counter) 1000)
   (= (distance kitchen kitchen) 1000)
   (= (distance sink sink) 1000)
   (= (distance drawer drawer) 1000)
   (= (distance dishwasher dishwasher) 1000)
   (= (distance fridge fridge) 1000)
   (= (distance table table) 1000)
   (= (distance start start) 1000)
   (= (distance somewhere room73a1) 30)
   (= (distance somewhere bookshelf) 30)
   (= (distance somewhere counter) 30)
   (= (distance somewhere kitchen) 30)
   (= (distance somewhere sink) 30)
   (= (distance somewhere drawer) 30)
   (= (distance somewhere dishwasher) 30)
   (= (distance somewhere fridge) 30)
   (= (distance somewhere table) 30)
   (= (distance somewhere start) 30)
   (= (distance room73a1 somewhere) 30)
   (= (distance room73a1 bookshelf) 30)
   (= (distance room73a1 counter) 30)
   (= (distance room73a1 kitchen) 30)
   (= (distance room73a1 sink) 9)
   (= (distance room73a1 drawer) 30)
   (= (distance room73a1 dishwasher) 30)
   (= (distance room73a1 fridge) 10)
   (= (distance room73a1 table) 9)
   (= (distance room73a1 start) 30)
   (= (distance bookshelf somewhere) 30)
   (= (distance bookshelf room73a1) 30)
   (= (distance bookshelf counter) 30)
   (= (distance bookshelf kitchen) 30)
   (= (distance bookshelf sink) 30)
   (= (distance bookshelf drawer) 30)
   (= (distance bookshelf dishwasher) 30)
   (= (distance bookshelf fridge) 30)
   (= (distance bookshelf table) 30)
   (= (distance bookshelf start) 30)
   (= (distance counter somewhere) 30)
   (= (distance counter room73a1) 30)
   (= (distance counter bookshelf) 30)
   (= (distance counter kitchen) 30)
   (= (distance counter sink) 30)
   (= (distance counter drawer) 30)
   (= (distance counter dishwasher) 30)
   (= (distance counter fridge) 30)
   (= (distance counter table) 30)
   (= (distance counter start) 30)
   (= (distance kitchen somewhere) 30)
   (= (distance kitchen room73a1) 30)
   (= (distance kitchen bookshelf) 30)
   (= (distance kitchen counter) 30)
   (= (distance kitchen sink) 30)
   (= (distance kitchen drawer) 30)
   (= (distance kitchen dishwasher) 30)
   (= (distance kitchen fridge) 30)
   (= (distance kitchen table) 30)
   (= (distance kitchen start) 30)
   (= (distance sink somewhere) 30)
   (= (distance sink room73a1) 9)
   (= (distance sink bookshelf) 30)
   (= (distance sink counter) 30)
   (= (distance sink kitchen) 30)
   (= (distance sink drawer) 30)
   (= (distance sink dishwasher) 30)
   (= (distance sink fridge) 3)
   (= (distance sink table) 3)
   (= (distance sink start) 30)
   (= (distance drawer somewhere) 30)
   (= (distance drawer room73a1) 30)
   (= (distance drawer bookshelf) 30)
   (= (distance drawer counter) 30)
   (= (distance drawer kitchen) 30)
   (= (distance drawer sink) 30)
   (= (distance drawer dishwasher) 30)
   (= (distance drawer fridge) 30)
   (= (distance drawer table) 30)
   (= (distance drawer start) 30)
   (= (distance dishwasher somewhere) 30)
   (= (distance dishwasher room73a1) 30)
   (= (distance dishwasher bookshelf) 30)
   (= (distance dishwasher counter) 30)
   (= (distance dishwasher kitchen) 30)
   (= (distance dishwasher sink) 30)
   (= (distance dishwasher drawer) 30)
   (= (distance dishwasher fridge) 30)
   (= (distance dishwasher table) 30)
   (= (distance dishwasher start) 30)
   (= (distance fridge somewhere) 30)
   (= (distance fridge room73a1) 10)
   (= (distance fridge bookshelf) 30)
   (= (distance fridge counter) 30)
   (= (distance fridge kitchen) 30)
   (= (distance fridge sink) 3)
   (= (distance fridge drawer) 30)
   (= (distance fridge dishwasher) 30)
   (= (distance fridge table) 0)
   (= (distance fridge start) 30)
   (= (distance table somewhere) 30)
   (= (distance table room73a1) 9)
   (= (distance table bookshelf) 30)
   (= (distance table counter) 30)
   (= (distance table kitchen) 30)
   (= (distance table sink) 3)
   (= (distance table drawer) 30)
   (= (distance table dishwasher) 30)
   (= (distance table fridge) 0)
   (= (distance table start) 30)
   (= (distance start somewhere) 30)
   (= (distance start room73a1) 30)
   (= (distance start bookshelf) 30)
   (= (distance start counter) 30)
   (= (distance start kitchen) 30)
   (= (distance start sink) 30)
   (= (distance start drawer) 30)
   (= (distance start dishwasher) 30)
   (= (distance start fridge) 30)
   (= (distance start table) 30)
   (openable rarm dishwasher)
   (openable rarm fridge)
   (openable rarm room73a1)
   (available sink)
   (available counter)
   (available kitchen)
   (available table)
   (available bookshelf)
   (available drawer)))
 (:goal (and (on bottle fridge) (forall (?at - spot) (not (open ?at)))))
 (:metric minimize (total-cost)))
