rosrun dynamic_reconfigure dynparam load /euclidean_clustering euclidean_clustering.yaml
rosrun dynamic_reconfigure dynparam load /multi_plane_estimate multi_plane_estimate.yaml
rosrun dynamic_reconfigure dynparam load /multisense multisense.yaml
