#!/usr/bin/env python
# -*- coding:utf-8 -*-

import rospy
import os
import re

from jsk_tools.sanity_lib import (okMessage, errorMessage, warnMessage,
                                  checkTopicIsPublished,
                                  checkROSMasterCLOSE_WAIT,
                                  checkNodeState)

from std_msgs.msg import Time

check_ocs_nodes = ["chesk_sanity_fc",
                   "dammy_tf_broadcaster",
                   "rviz_status",
                   "ocs_dynamic_reconfigure",
                   "button_checker",
                   "stair_marker",
                   'calc_box_plane',
                   "spacenav_client",
                   "robot_idle_watch",
                   "time_update_text",
                   'interpret_object',
                   "filter_bbox_position",
                   'b_control_client',
                   'calc_drive_tf',
                   "offset_bbox_from_plane",
                   "static_transform_bounding_box_array",
                   'wrench_fft',
                   'joy_to_twist',
                   "fc_dynamic_reconfigure",
                   'fft_data',
                   'drill_button_publisher',
                   "ar_pose_to_pose",
                   'fft_data',
                   'polygon_to_centroid',
                   "CarPathVisualizer",
                   "magnetometer_to_direction",
                   "SteeringAngleMarker",
                   "google_translation_talk",
                   "timer_talker",
                   "nearest_box_indices",
                   'revice_button_pose',
                   'hand_box_publisher',
                   'rect_publisher',
                   'revice_button_pose',
                   "task_state_manager",
                   "check_sanity_ocs",
                   "check_hand",
                   "geometry_msgs",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "ocs_executive",
                   "std_srvs",
                   "jsk_footstep_msgs",
                   "image_view2",
                   "geometry_msgs",
                   "topic_tools",
                   "jsk_recognition_msgs",
                   "drc_com_common",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "drc_task_common",
                   "drc_task_common",
                   "std_msgs",
                   "smach_msgs",
                   "jsk_topic_tools",
                   "rv_map_publiser",
                   "eus_commandserver",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "drc_task_common",
                   "test",
                   "dynamic_reachability_publisher",
                   "rosgraph_msgs",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "jsk_rviz_plugins",
                   "drc_task_common",
                   "jsk_footstep_msgs",
                   "drc_task_common",
                   "jsk_footstep_msgs",
                   "joint_states_storage",
                   "jsk_footstep_msgs",
                   "drc_task_common",
                   "sensor_msgs",
                   "jsk_footstep_msgs",
                   "ocs_robot_interface",
                   "trans_ros_bridge",
                   "jsk_footstep_msgs",
                   "std_msgs",
                   "drc_com_common",
                   "hrpsys_ros_bridge",
                   "geometry_msgs",
                   "fc_basic_info_publisher",
                   "rviz_menu_server",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "jsk_recognition_msgs",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "drc_task_common",
                   "walk_to_object",
                   "sensor_msgs",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "drc_task_common",
                   "move_base_msgs",
                   "robot_main",
                   "set_recog_param",
                   "jsk_footstep_msgs",
                   "jsk_footstep_msgs",
                   "trans_ros_bridge",
                   "drc_com_common",
                   "tf2_msgs",
                   "dynamic_tf_publisher",
                   "hrpsys_ros_bridge",
                   "geometry_msgs",
                   "sensor_msgs",
                   "ocs_basic_info_publisher",
                   "teleop_test",
                   "geometry_msgs",
                   "ocs_executive",
                   "std_srvs",
                   "jsk_topic_tools",
                   "jsk_footstep_msgs",
                   "image_view2",
                   "geometry_msgs",
                   "drc_com_common",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "pcl_msgs",
                   "std_msgs",
                   "geometry_msgs",
                   "staro_driving_controller",
                   "jaxon_red_driving_interface_on_polaris_xp900",
                   "std_srvs",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "robot_driving_controller",
                   "hrp2jsknt_driving_interface_on_polaris_xp900",
                   "tf_car_center_publisher",
                   "jaxon_driving_interface_on_polaris_xp900",
                   "drc_com_common",
                   "drc_task_common",
                   "vehicle_ocs_executive",
                   "staro_driving_controller_on_polaris_xp900",
                   "tf_car_center_publisher",
                   "hrp2jsknt_driving_interface_on_polaris_xp900",
                   "drc_com_common",
                   "jsk_interactive_marker",
                   "jsk_recognition_msgs",
                   "drc_task_common",
                   "geometry_msgs",
                   "test_steering_coords_estimation",
                   "hrp2jsknts_driving_interface_on_polaris_xp900",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "drc_com_common",
                   "vehicle_fc_executive",
                   "request_ik_from_marker",
                   "jsk_rviz_plugins",
                   "jsk_rviz_plugins",
                   "jsk_recognition_msgs",
                   "jsk_interactive_marker",
                   "jsk_interactive_marker",
                   "drc_task_common",
                   "drc_task_common",
                   "visualization_msgs",
                   "test",
                   "jsk_recognition_msgs",
                   "sensor_msgs",
                   "robot_bbox",
                   "jsk_footstep_msgs",
                   ]

def main():
    rospy.init_node("check_sanity_ocs")

    host = re.match("http://([0-9a-zA-Z]*):.*", os.environ["ROS_MASTER_URI"]).groups(0)[0]
    checkROSMasterCLOSE_WAIT(host)

    #Check Input Device
    checkTopicIsPublished("/b_control/joy", None,
                          "MIDI Controller seems to work",
                          "MIDI Controller doesn't publish. Does you connect?")
    checkTopicIsPublished("/ocs/joy", None,
                          "XBox Controller seems to work",
                          "XBox Controller doesn't publish. Did you connect?")

    checkTopicIsPublished(
        "/fc_from_ocs_eus/last_publish_output_time",
        Time,
        "[ocs] Silverhammer lowspeed protocol is working",
        "[ocs] Silverhammer lowspeed protocol is not working",
        5,
        [["/fc_from_ocs_eus/last_received_time", Time],
         ["/fc_from_ocs_eus/output", Time],
         ["/fc_from_ocs_low_speed/last_publish_output_time", Time],
         ["/fc_from_ocs_low_speed/last_received_time", Time],
         ["/fc_from_ocs_low_speed/output", Time],
         ["/fc_from_ocs_reconfigure/last_publish_output_time", Time],
         ["/fc_from_ocs_reconfigure/last_received_time", Time],
         ["/fc_from_ocs_reconfigure/output", Time],
         ["/fc_from_ocs_vehicle/last_publish_output_time", Time],
         ["/fc_from_ocs_vehicle/last_received_time", Time],
         ["/fc_from_ocs_vehicle/output", Time],
         ["/fc_to_ocs_basic_low_speed/input", Time],
         ["/fc_to_ocs_basic_low_speed/last_input_received_time", Time],
         ["/fc_to_ocs_basic_low_speed/last_send_time", Time],
         ["/fc_to_ocs_eus/input", Time],
         ["/fc_to_ocs_eus/last_input_received_time", Time],
         ["/fc_to_ocs_eus/last_send_time", Time],
         ["/fc_to_ocs_low_speed/input", Time],
         ["/fc_to_ocs_low_speed/last_input_received_time", Time],
         ["/fc_to_ocs_low_speed/last_send_time", Time],
         ["/fc_to_ocs_vehicle/input", Time],
         ["/fc_to_ocs_vehicle/last_input_received_time", Time],
         ["/fc_to_ocs_vehicle/last_send_time"]])

    # check Node State
    for node in check_ocs_nodes:
        checkNodeState(node, needed=True)

if __name__ == "__main__":
    main()
