#!/usr/bin/env python

import sys

import roslib
pkg = 'drc_task_common'

import imp
try:
    imp.find_module(pkg)
except:
    roslib.load_manifest(pkg)

from rqt_gui.main import Main

import drc_task_common
import drc_task_common.drc_teleop_interface

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg))
